#!/bin/bash
#A faire sur le serveur
#Créer les utilisateur-trice-s
#Leur donner les droits Admin
#Autoriser les connections ssh
#Se connecter ssh utilisateur@serveur
#cd /volume1/homes
#ls -al
#sudo chmod 755 /volume1/homes/utilisateur
#sudo vi /etc/passwd vérifier que les utilisateurs ont /bin/sh à la fin
#Pour chaque utilisateur-trice 
#mkdir ~/.ssh
#chmod 0700 ~/.ssh
#touch ~/.ssh/authorized_keys
#chmod 0644 ~/.ssh/authorized_keys
#ssh-keygen
#Puis exécuter  ce script pour envoyer les clés liées à l'ordi

#gnome-terminal -x ./Configurer_Utilisateur_Backup_sur_Synology
# Déclarer les variables
SERVEURLG=cemealg.myftp.org
SERVEURBX=cemeabx.myftp.org
echo "Configuration à faire sur le serveur de : "
select LIEU in "Bruxelles" "Liège" "Quitter"
do
		    case $LIEU in
		        "Bruxelles")
		            	echo "Identifiant de l'utilisateur"
				read ID
				if [ -f ~/.ssh/id_rsa.pub ]
				then
				ssh-copy-id -i ~/.ssh/id_rsa.pub $ID@$SERVEURBX
				else 
				ssh-keygen
				ssh-copy-id -i ~/.ssh/id_rsa.pub $ID@$SERVEURBX
				fi
				echo -e "Fini\n(appuyez sur \"Entrée\" pour terminer)"
				read
				break
		            	;;
		        "Liège")
		            	echo "Identifiant de l'utilisateur"
				read ID
				if [ -f ~/.ssh/id_rsa.pub ]
				then
				ssh-copy-id -i ~/.ssh/id_rsa.pub $ID@$SERVEURLG
				else 
				ssh-keygen
				ssh-copy-id -i ~/.ssh/id_rsa.pub $ID@$SERVEURLG
				fi
				echo -e "Fini\n(appuyez sur \"Entrée\" pour terminer)"
				read
				break
				;;
		        "Quitter")
		            	break
		           	;;
		        *) echo "Choix invalide";;
		    esac
		done
exit
